### ISSUE TITLE
Update to new chrome extension manifest

### ISSUE THREAD

**Issue by zoomido** [mogenson/esc2ctrl#2]
Hi! 
Just found this plugin and wanted to use it with my swedish keyboard. I was going to try to change the language in the manifest but realized that v2 is deprecated: https://developer.chrome.com/docs/extensions/migrating/
Which leads me to two questions:

Is it possible/easy to get this plugin updated to latest v3?
Is it as simple as changing language in the manifest to use a different keyboard layout?

Best regards!

**Comment by mogenson** [comment]
Hi, thanks for letting me know. Unfortunately I don't have a Chromebook anymore or very much time to work on this project. However, if you'd like to update the manifest and send a pull request, I'd be happy to merge it!

**Comment by mogenson** [comment]
Fixed with #3
